### PR TITLE
fix: handle user deletion config drift

### LINKED ISSUE #208: Resource `coderd_user`: Plan fails when user was deleted outside of terraform
When a user created via the coderd provider is removed outside of terraform, the plan fails because it cannot find the user.
```hcl
resource "coderd_user" "user" {
  username = "myuser"
  email = "myuser@myorg.com"
  name = "My User"
  roles = []
  login_type = "oidc"
}
```
```log
╷
│ Error: Client Error
│ 
│   with coderd_user.user,
│   on users.tf line 1, in resource "coderd_user" "user":
│    1: resource "coderd_user" "user" {
│ 
│ Unable to get current user, got error: GET
│ https://<REDACTED url>/api/v2/users/<REDACTED user id>:
│ unexpected status code 400: "user" must be an existing uuid or username.
│ 	Error: queried user="<REDACTED user id>"
╵
```

I would have expected the provider to mark this as deleted instead of running into an error

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes #208.

Querying `api/v2/users/{ID}` returns a valid response for deleted users, as deleted users in `coderd` are merely tombstoned. To handle this, we perform an additional query by username. If the user has been deleted, the username will be available, or belong to a user with a different ID, in which case we can mark the user resource as deleted.

Also has the `isNotFound` check include the specific response for when a user does not exist:
```
sdkErr.StatusCode() == http.StatusBadRequest && strings.Contains(sdkErr.Message, "must be an existing uuid or username")
```

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#209** <a href="https://app.graphite.dev/github/pr/coder/terraform-provider-coderd/209?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/terraform-provider-coderd/209?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: internal/provider/user_resource.go [hunk 1]
```diff
@@ -274,6 +275,23 @@ func (r *UserResource) Read(ctx context.Context, req resource.ReadRequest, resp
 	data.LoginType = types.StringValue(string(user.LoginType))
 	data.Suspended = types.BoolValue(user.Status == codersdk.UserStatusSuspended)
 
+	// Also query by username to check for deletion or username reassignment
```
Comment (deansheather) [inline internal/provider/user_resource.go:278]: This comment should say why this is necessary from an API point of view. "The user-by-ID API always returns a user with no indication in the response that it's deleted or not, but the user-by-username API will never return deleted users."

File: internal/provider/user_resource.go [hunk 2]
```diff
@@ -274,6 +275,23 @@ func (r *UserResource) Read(ctx context.Context, req resource.ReadRequest, resp
...
+	userByName, err := client.User(ctx, data.Username.ValueString())
+	if err != nil {
+		if isNotFound(err) {
+			resp.Diagnostics.AddWarning("Client Warning", fmt.Sprintf("User with ID %q not found. Marking as deleted.", data.ID.ValueString()))
```
Comment (deansheather) [inline internal/provider/user_resource.go:282]: Shouldn't this read "user with username not found"? These errors should probably be more descriptive and say that the terraform-managed user was deleted outside of terraform

File: internal/provider/user_resource.go [hunk 3]
```diff
@@ -274,6 +275,23 @@ func (r *UserResource) Read(ctx context.Context, req resource.ReadRequest, resp
...
+			resp.State.RemoveResource(ctx)
+			return
+		}
+		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to get current user, got error: %s", err))
```
Comment (deansheather) [inline internal/provider/user_resource.go:286]: error should say "by username"

File: internal/provider/user_resource.go [hunk 4]
```diff
@@ -274,6 +275,23 @@ func (r *UserResource) Read(ctx context.Context, req resource.ReadRequest, resp
...
+		return
+	}
+	if userByName.ID != data.ID.ValueUUID() {
+		resp.Diagnostics.AddWarning("Client Error", fmt.Sprintf("The username %q has been reassigned to a new user. Marking as deleted.", user.Username))
```
Comment (deansheather) [inline internal/provider/user_resource.go:290]: "that isn't managed by terraform" or something so they know it's not a terraform provider problem when it inevitably fails to create a new resource over the top of it

File: internal/provider/util.go [hunk 5]
```diff
@@ -110,5 +111,15 @@ func memberDiff(currentMembers []uuid.UUID, plannedMembers []UUID) (add, remove
...
 func isNotFound(err error) bool {
 	var sdkErr *codersdk.Error
-	return errors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusNotFound
+	if !errors.As(err, &sdkErr) {
+		return false
+	}
+	if sdkErr.StatusCode() == http.StatusNotFound {
+		return true
+	}
+	// `httpmw/ExtractUserContext` returns a 400 w/ this message if the user is not found
```
Comment (deansheather) [inline internal/provider/util.go:120]: 😮‍💨

**Review by deansheather — APPROVED** [review]

**Comment by ethanndickson** [comment]
### Merge activity

* **Apr 15, 9:28 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/terraform-provider-coderd/209).
